// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type SaveAllTab struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Titles    []string
	Urls      []string
}

type SaveWebpage struct {
	ID        uuid.UUID
	CreateAt  time.Time
	UpdatedAt time.Time
	HasRead   sql.NullBool
	Title     string
	Url       string
}

type TabTag struct {
	TagID     uuid.UUID
	WebpageID uuid.UUID
}

type Tag struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Show      sql.NullBool
	Tag       string
}
